### ISSUE TITLE
bullet 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-510#1]
there are strangely formatted bullet points
in the overview, you are not using subsections

**Comment by techvigil** [comment]
hi Professor, I wanted to make sub-sections in overview without providing any numbering to them, if that is not ok, I can change them to be numbered sub sections

**Comment by laszewsk** [comment]
this is not how papers do it. if you need them you need to than use description lists

**Comment by laszewsk** [comment]
description lists are not a substitute for section and subsections.

**Comment by techvigil** [comment]
I will update them to make as sub sections.

**Comment by techvigil** [comment]
Done with the latest commit.
